### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Salamandar** [Salamandar/stm32Libs#1]
- Stm32f429zi Discovery modules :
  - [ ] User Button
  - [ ] On-board leds
  - [ ] Delays and alarms
  - [ ] STMPE811 driver (Touchscreen)
  - [ ] CPU load ?
  - [ ] ILI9341 driver (LCD driver)
  - [ ] DMA (direct memory access, general purpose)
  - [ ] DMA2D (direct memory access for graphic data to LCD, "hardware graphic accel")
  - [ ] LTDC high-level library (ILI9341, DMA2D, etc)
  - [ ] USB OTG
  - [ ] USB serial console
  - [ ] L3GD20 driver (Gyroscope MEMS) _i2c/SPI_
  - [ ] LIS302DL/LIS3DSH driver(s) (Accelerometer) _SPI_
  - [ ] Fat filesystem

- [ ] Alternate functions for GPIOs

- [ ] nrf24l01 (802.15.4 RF module)

**Comment by brabo** [comment]
Hiya, I just saw your issue over at libopencm3. As @kuldeepdhaka I'm involved with unicore-mx, which may be interesting for your project as well. I wrote a very basic stmpe811 driver some time ago, without I2C event interrupts or DMA here https://github.com/brabo/stm32f429i-disco-stmpe811
I have as WIP also versions with I2C event interrupts and DMA, if you are interested, let me know and I will point you to the repo for that once published ;)
For FAT perhaps ChaNs FatFS or Petite FatFS would work?

Greetings!
